use std::{fs, path::Path, process::Command, time::Instant};

use anyhow::Context;
use crossterm::event::{Event, KeyCode, KeyEvent, KeyEventKind, KeyModifiers};
use minitask::{
    editor,
    store::{Store, lock_store},
    ui::App,
};
use ratatui::{Terminal, backend::TestBackend};
use tempfile::tempdir;

#[test]
fn original_go_markdown_and_state_survive_index_upgrade() -> anyhow::Result<()> {
    let dir = tempdir()?;
    fs::create_dir(dir.path().join("Smoke"))?;
    let path = dir.path().join("Smoke/tasks.md");
    fs::write(
        &path,
        "# Smoke\n\n## [x] First task\nEdited through Emacs\nEdited through the TUI\n\n",
    )?;
    let file = fs::OpenOptions::new().write(true).open(&path)?;
    file.set_modified(
        std::time::UNIX_EPOCH + std::time::Duration::from_nanos(1788845109018582600),
    )?;
    drop(file);
    // Captured from the Go executable before migration, not generated by Rust.
    let legacy = r#"{"Version":1,"Files":{"Smoke":{"Size":72,"ModTime":1788845109018582600,"Hash":"8acbbe4443e7bf97d8ce062209e318e045a8adda0fe3256c19aa50101f9eed08","Tasks":[{"Title":"First task","Notes":"Edited through Emacs\nEdited through the TUI","Done":true,"Line":3,"Offset":13}]}}}"#;
    fs::write(dir.path().join(".index.json"), legacy)?;
    fs::write(dir.path().join(".state.json"), r#"{"Workspace":"Smoke"}"#)?;
    let store = Store::open(dir.path()).context("loading original Go cache")?;
    assert_eq!(store.parsed, 1);
    assert_eq!(Store::open(dir.path())?.parsed, 0);
    assert_eq!(
        fs::read_to_string(&path)?,
        "# Smoke\n\n## [x] First task\nEdited through Emacs\nEdited through the TUI\n\n"
    );
    let mut app = App::new(store, "nvim".into());
    assert_eq!(app.workspace(), "Smoke");
    let index = app.store.files["Smoke"].clone();
    app.store
        .toggle("Smoke", &index.tasks[0])
        .context("toggling task loaded from Go cache")?;
    assert!(fs::read_to_string(path)?.contains("## [ ] First task"));
    Ok(())
}

#[test]
fn markdown_is_preserved_and_stale_selection_cannot_overwrite_changes() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let mut store = Store::open(dir.path())?;
    store.create_workspace("日本語 project")?;
    let original = "\u{feff}# project\r\n\r\n## [ ] リリース\r\n詳細メモ\r\n```md\r\n## [x] example\r\n```\r\n\r\n## [X] 完了\r\n保持するメモ";
    fs::write(store.path("日本語 project"), original)?;
    store.refresh(true, None)?;
    let index = store.files["日本語 project"].clone();
    assert_eq!(index.tasks.len(), 2);
    assert_eq!(index.tasks[0].line, 3);
    assert!(index.tasks[1].done);
    assert!(index.tasks[0].notes.contains("## [x] example"));
    store.toggle("日本語 project", &index.tasks[0])?;
    assert_eq!(
        fs::read_to_string(store.path("日本語 project"))?,
        original.replacen("## [ ]", "## [x]", 1)
    );
    let external = "# external\n\n## [ ] Other task\n";
    fs::write(store.path("日本語 project"), external)?;
    assert!(store.toggle("日本語 project", &index.tasks[0]).is_err());
    assert_eq!(fs::read_to_string(store.path("日本語 project"))?, external);
    Ok(())
}

#[test]
fn incremental_cache_tracks_individual_files_and_empty_workspaces() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let mut store = Store::open(dir.path())?;
    store.create_workspace("alpha")?;
    store.create_workspace("beta")?;
    let source = store.add_task("alpha", "日本語 task")?;
    let path = dir.path().join("alpha").join(&source);
    let mut reopened = Store::open(dir.path())?;
    assert_eq!(reopened.parsed, 0);
    fs::write(&path, "- [ ] changed\nnew details\n")?;
    assert_eq!(reopened.refresh(false, None)?, 1);
    assert!(reopened.files["beta"].tasks.is_empty());
    fs::write(dir.path().join(".index.json"), "broken")?;
    let mut rebuilt = Store::open(dir.path())?;
    assert_eq!(rebuilt.parsed, 1);
    let file = fs::OpenOptions::new().write(true).open(&path)?;
    let modified = file.metadata()?.modified()?;
    fs::write(&path, "- [ ] CHANGED\nnew details\n")?;
    file.set_modified(modified)?;
    rebuilt.refresh(false, Some(&format!("alpha/{source}")))?;
    assert_eq!(rebuilt.files["alpha"].tasks[0].title, "CHANGED");
    drop(file);
    let revision = rebuilt.revision;
    fs::remove_file(path)?;
    assert_eq!(rebuilt.refresh(false, None)?, 0);
    assert!(rebuilt.files["alpha"].tasks.is_empty());
    assert_ne!(rebuilt.revision, revision);
    Ok(())
}

#[test]
fn incomplete_notes_remain_editable_but_cannot_hide_new_tasks() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let mut store = Store::open(dir.path())?;
    store.create_workspace("draft")?;
    let original = "\u{feff}## [ ] draft\nnotes\n```\n## [ ] example";
    fs::write(store.path("draft"), original)?;
    store.refresh(true, None)?;
    let index = store.files["draft"].clone();
    assert_eq!(index.tasks.len(), 1);
    store.add_task("draft", "independent task")?;
    assert_eq!(store.files["draft"].tasks.len(), 2);
    store.toggle("draft", &index.tasks[0])?;
    assert_eq!(
        fs::read_to_string(store.path("draft"))?,
        original.replacen("[ ]", "[x]", 1)
    );
    Ok(())
}

#[test]
fn invalid_inputs_and_second_writer_are_rejected() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let lock = lock_store(dir.path())?;
    assert!(lock_store(dir.path()).is_err());
    drop(lock);
    let _lock = lock_store(dir.path())?;
    let mut store = Store::open(dir.path())?;
    for name in [
        "",
        "../escape",
        "..",
        ".hidden",
        "a/b",
        "a\\b",
        "CON",
        "NUL.txt",
        "trail.",
        "line\nbreak",
    ] {
        assert!(store.create_workspace(name).is_err(), "accepted {name:?}");
    }
    store.create_workspace("valid")?;
    assert!(store.create_workspace("valid").is_err());
    assert!(store.add_task("valid", "inject\n## [x] task").is_err());
    Ok(())
}

fn key(app: &mut App, code: KeyCode) -> anyhow::Result<()> {
    app.event(Event::Key(KeyEvent::new(code, KeyModifiers::NONE)))?;
    Ok(())
}

fn type_text(app: &mut App, value: &str) -> anyhow::Result<()> {
    for c in value.chars() {
        key(app, KeyCode::Char(c))?;
    }
    Ok(())
}

#[test]
fn keyboard_workflow_search_small_screen_and_workspace_restore() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let mut app = App::new(Store::open(dir.path())?, "nvim".into());
    key(&mut app, KeyCode::Char('n'))?;
    type_text(&mut app, "個人 workspace")?;
    key(&mut app, KeyCode::Enter)?;
    for title in ["日本語タスク", "another task"] {
        key(&mut app, KeyCode::Char('a'))?;
        type_text(&mut app, title)?;
        key(&mut app, KeyCode::Enter)?;
    }
    key(&mut app, KeyCode::Char('/'))?;
    type_text(&mut app, "日本語")?;
    key(&mut app, KeyCode::Enter)?;
    key(&mut app, KeyCode::Char(' '))?;
    assert!(app.store.files["個人 workspace"].tasks[0].done);
    assert!(!app.store.files["個人 workspace"].tasks[1].done);
    key(&mut app, KeyCode::Char('5'))?;
    let mut terminal = Terminal::new(TestBackend::new(100, 30))?;
    terminal.draw(|frame| app.draw(frame))?;
    let buffer = terminal.backend().buffer();
    let mut rendered = String::new();
    for y in 0..30 {
        let mut x = 0;
        while x < 100 {
            let symbol = buffer[(x, y)].symbol();
            rendered.push_str(symbol);
            x += unicode_width::UnicodeWidthStr::width(symbol).max(1) as u16;
        }
    }
    assert!(rendered.contains("日本語タスク"), "{rendered:?}");
    key(&mut app, KeyCode::Esc)?;
    key(&mut app, KeyCode::Char('n'))?;
    type_text(&mut app, "work")?;
    key(&mut app, KeyCode::Enter)?;
    app.save_state()?;
    assert_eq!(
        App::new(Store::open(dir.path())?, "nvim".into()).workspace(),
        "work"
    );
    for (w, h) in [(8, 3), (40, 12), (120, 40)] {
        let mut terminal = Terminal::new(TestBackend::new(w, h))?;
        terminal.draw(|frame| app.draw(frame))?;
    }
    app.event(Event::Paste("qna\n".into()))?;
    assert!(!app.quit);
    app.event(Event::Key(KeyEvent::new_with_kind(
        KeyCode::Char('q'),
        KeyModifiers::NONE,
        KeyEventKind::Release,
    )))?;
    assert!(
        !app.quit,
        "Windows key release must not trigger a second action"
    );
    key(&mut app, KeyCode::Char('q'))?;
    assert!(app.quit);
    Ok(())
}

#[test]
fn editor_precedence_quotes_and_argv() -> anyhow::Result<()> {
    assert_eq!(
        editor::choose(Some("explicit"), Some("visual"), Some("editor")),
        "explicit"
    );
    assert_eq!(
        editor::choose(None, Some("visual"), Some("editor")),
        "visual"
    );
    assert_eq!(editor::choose(None, None, Some("editor")), "editor");
    assert_eq!(editor::choose(None, None, None), "nvim");
    assert_eq!(
        editor::split(r#""C:\Program Files\Editor\edit.exe" --wait "two words""#)?,
        [r"C:\Program Files\Editor\edit.exe", "--wait", "two words"]
    );
    let command = editor::command("emacs -nw", Path::new("C:/tasks & notes/tasks.md"), 7)?;
    let args: Vec<_> = command
        .get_args()
        .map(|a| a.to_string_lossy().into_owned())
        .collect();
    assert_eq!(args, ["-nw", "+7", "--", "C:/tasks & notes/tasks.md"]);
    Ok(())
}

#[test]
fn nvim_and_emacs_edit_the_selected_line() -> anyhow::Result<()> {
    let editors = [
        (
            "nvim",
            std::env::var("MINITASK_TEST_NVIM").unwrap_or("nvim".into()),
        ),
        (
            "emacs",
            std::env::var("MINITASK_TEST_EMACS").unwrap_or("emacs".into()),
        ),
    ];
    for (kind, exe) in editors {
        if Command::new(&exe).arg("--version").output().is_err() {
            eprintln!(
                "Skipping {kind}: set MINITASK_TEST_{} to test an executable outside PATH",
                kind.to_uppercase()
            );
            continue;
        }
        let dir = tempdir()?;
        let mut store = Store::open(dir.path())?;
        store.create_workspace("space 日本語")?;
        store.add_task("space 日本語", "edit me")?;
        let task = &store.files["space 日本語"].tasks[0];
        let base = editor::command(&exe, &store.task_path("space 日本語", task)?, task.line)?;
        let mut command = Command::new(base.get_program());
        let args: Vec<_> = base.get_args().collect();
        if kind == "nvim" {
            command
                .args(["--headless", "-u", "NONE", "-i", "NONE", "-n"])
                .args(&args[..args.len() - 2])
                .args([
                    "-c",
                    "call setline('.', '- [ ] edited [due:: 2028-03-01]')",
                    "-c",
                    "wq",
                ])
                .args(&args[args.len() - 2..]);
        } else {
            command.args(["--batch", "--quick", "--eval", "(add-hook 'kill-emacs-hook (lambda () (delete-region (line-beginning-position) (line-end-position)) (insert \"- [ ] edited [due:: 2028-03-01]\") (save-buffer)))"]).args(&args);
        }
        let output = command
            .current_dir(dir.path())
            .env("NVIM_LOG_FILE", dir.path().join("nvim.log"))
            .output()?;
        assert!(
            output.status.success(),
            "{kind}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        store.refresh(false, Some("space 日本語"))?;
        assert_eq!(
            store.files["space 日本語"].tasks[0].title, "edited",
            "{kind}"
        );
        assert_eq!(
            store.files["space 日本語"].tasks[0].due,
            Some(minitask::dates::parse_date("2028-03-01")?)
        );
    }
    Ok(())
}

#[test]
#[ignore = "manual index benchmark"]
fn index_benchmark() -> anyhow::Result<()> {
    let dir = tempdir()?;
    let doc: String = (0..100)
        .map(|i| format!("- [ ] タスク {i} [scheduled:: 2026-09-10] [due:: 2026-09-12]\n  日本語の詳細メモと調査結果を残す。\n\n"))
        .collect();
    for i in 0..100 {
        let path = dir.path().join(format!("project-{i:03}"));
        fs::create_dir(&path)?;
        fs::write(path.join("tasks.md"), &doc)?;
    }
    let mut store = Store::open(dir.path())?;
    for mode in ["rebuild", "warm-start", "unchanged-refresh"] {
        let mut samples = Vec::new();
        for _ in 0..3 {
            let start = Instant::now();
            for _ in 0..30 {
                match mode {
                    "rebuild" => {
                        store.refresh(true, None)?;
                    }
                    "warm-start" => {
                        Store::open(dir.path())?;
                    }
                    _ => {
                        store.refresh(false, None)?;
                    }
                }
            }
            samples.push(start.elapsed().as_secs_f64() * 1000.0 / 30.0);
        }
        samples.sort_by(f64::total_cmp);
        println!(
            "{mode}: median {:.3} ms (100 files, 10000 tasks)",
            samples[1]
        );
    }
    Ok(())
}
